services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: wopen
  MYSQL_ROOT_PASSWORD: root

types:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y mysql-client default-libmysqlclient-dev python-mysqldb
    gdal-bin libproj-dev proj-data proj-bin binutils
  - pip install -r requirements/test.txt
  - cd whats-open/
  - export WOPEN_SECRET_KEY=$(dd if=/dev/urandom count=100 | tr -dc "A-Za-z0-9"
    | fold -w 60 | head -n1 2>/dev/null)
  - export WOPEN_EMAIL_DOMAIN="@masonlive.gmu.edu"
  - export WOPEN_DB_NAME="wopen"
  - export WOPEN_DB_USER="root"
  - export WOPEN_DB_PASSWORD="root"
  - export WOPEN_DB_HOST="mysql"
  - export WOPEN_DB_PORT=3306
  - export WOPEN_SUPERUSER=admin
  - python manage.py makemigrations
  - python manage.py makemigrations api
  - python manage.py migrate
  - echo "from django.contrib.auth import get_user_model; User =
    get_user_model(); User.objects.create_superuser('root',
    'root@srct.gmu.edu', 'root') " | python manage.py shell

whats-open-py3.5:
  image: library/python:3.5
  type: test
  script:
    - echo "Done 😄"
