version: '3'
services:
  db:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - wopen_net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: wopen
      MYSQL_USER: wopen
      MYSQL_PASSWORD: wopen

  api:
    image: whats-open-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - wopen_net
    ports:
      - '8000:8000'
    command: /bin/bash ./startup.sh
    volumes:
      - .:/whats-open
    depends_on:
      - db
    environment:
      - WOPEN_EMAIL_DOMAIN=@masonlive.gmu.edu
      - WOPEN_DB_NAME=wopen
      - WOPEN_DB_USER=wopen
      - WOPEN_DB_PASSWORD=wopen
      - WOPEN_DB_HOST=db
      - WOPEN_DB_PORT=3306
      - WOPEN_SUPERUSER=admin

networks:
  wopen_net: