version: '2'
services:
  wopen_web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    command: /bin/bash ./startup.sh
    volumes:
      - .:/whats_open
    depends_on:
      - wopen_db
    environment:
      - WOPEN_EMAIL_DOMAIN=@masonlive.gmu.edu
      - WOPEN_DB_NAME=wopen
      - WOPEN_DB_USER=wopen
      - WOPEN_DB_PASSWORD=wopen
      - WOPEN_DB_HOST=wopen_db
      - WOPEN_DB_PORT=3306
      - WOPEN_SUPERUSER=admin
  wopen_db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: wopen
      MYSQL_USER: wopen
      MYSQL_PASSWORD: wopen