version: "3"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wopen
      MYSQL_USER: wopen
      MYSQL_PASSWORD: wopen

  api:
    build: .
    ports:
      - "8000:8000"
    command: ./docker-startup.sh
    depends_on:
      - db
    environment:
      - WOPEN_EMAIL_DOMAIN=@masonlive.gmu.edu
      - WOPEN_DB_NAME=wopen
      - WOPEN_DB_USER=wopen
      - WOPEN_DB_PASSWORD=wopen
      - WOPEN_DB_HOST=db
      - WOPEN_DB_PORT=3306
      - WOPEN_SUPERUSER=admin
